export const excelCourses = [
	{
		id: 1,
		img: '/images/excel/1.jpg',
		title: 'Microsoft Excel - Excel course',
		desc: 'from beginner to advanced',
		instructor: 'Jose Portilla, Pierian Training',
		stars: 3,
		rate: 4,
		rateNumber: '403,83',
		price: 'EL109.99',
		discount: 'EL1,879.99',
	},
	{
		id: 2,
		img: '/images/excel/2.jpg',
		title: 'Zero to Hero in Excel',
		desc: 'Complete Excel guide 2024A Beginner',
		instructor: 'start-tech academy',
		stars: 4,
		rate: 4.2,
		rateNumber: '24,783',
		price: 'EL209.99',
		discount: 'EL1,555.99',
	},
	{
		id: 3,
		img: '/images/excel/3.jpg',
		title: 'Microsoft Excel Weekender',
		desc: 'crash course',
		instructor: 'start-tech academy',
		stars: 5,
		rate: 4.9,
		rateNumber: '203,83',
		price: 'EL309.99',
		discount: 'EL1,999.99',
	},
	{
		id: 4,
		img: '/images/excel/4.jpg',
		title: 'Ms Excel/Excel 2023',
		desc: 'The Complete Introduction to Excel',
		instructor: 'yassin marko',
		stars: 4,
		rate: 4.6,
		rateNumber: '503,83',
		price: 'EL250.99',
		discount: 'EL1,222.99',
	},
	{
		id: 5,
		img: '/images/excel/5.jpg',
		title: 'Microsoft Excel - Excel course',
		desc: 'from beginner to advanced',
		instructor: 'Jose Portilla, Pierian Training',
		stars: 3,
		rate: 4,
		rateNumber: '403,83',
		price: 'EL109.99',
		discount: 'EL1,879.99',
	},
	{
		id: 6,
		img: '/images/excel/1.jpg',
		title: 'Microsoft Excel - Excel course',
		desc: 'from beginner to advanced',
		instructor: 'Jose Portilla, Pierian Training',
		stars: 3,
		rate: 4,
		rateNumber: '403,83',
		price: 'EL109.99',
		discount: 'EL1,879.99',
	},
];

export const pythonCourses = [
	{
		id: 1,
		img: '/images/python/1.jpg',
		title: 'Microsoft python - python course',
		desc: 'from beginner to advanced',
		instructor: 'Jose Portilla, Pierian Training',
		stars: 3,
		rate: 4,
		rateNumber: '403,83',
		price: 'EL109.99',
		discount: 'EL1,879.99',
		bestSeller: '',
	},
	{
		id: 2,
		img: '/images/python/2.jpg',
		title: 'Zero to Hero in python',
		desc: 'Complete python guide 2024',
		instructor: 'start-tech academy',
		stars: 4,
		rate: 4.2,
		rateNumber: '24,783',
		price: 'EL209.99',
		discount: 'EL1,555.99',
		bestSeller: 'best seller',
	},
	{
		id: 3,
		img: '/images/python/3.jpg',
		title: 'Microsoft python Weekender',
		desc: 'crash course',
		instructor: 'start-tech academy',
		stars: 5,
		rate: 4.9,
		rateNumber: '203,83',
		price: 'EL309.99',
		discount: 'EL1,999.99',
		bestSeller: '',
	},
	{
		id: 4,
		img: '/images/python/4.jpg',
		title: 'Ms python/python 2023',
		desc: 'The Complete Introduction to python',
		instructor: 'yassin marko',
		stars: 4,
		rate: 4.6,
		rateNumber: '503,83',
		price: 'EL250.99',
		discount: 'EL1,222.99',
		bestSeller: '',
	},
	{
		id: 5,
		img: '/images/python/5.jpg',
		title: 'Microsoft python',
		desc: 'from beginner to advanced',
		instructor: 'Jose Portilla, Pierian Training',
		stars: 3,
		rate: 4,
		rateNumber: '403,83',
		price: 'EL109.99',
		discount: 'EL1,879.99',
		bestSeller: 'best seller',
	},
	{
		id: 6,
		img: '/images/python/1.jpg',
		title: 'Microsoft python - python course',
		desc: 'from beginner to advanced',
		instructor: 'Jose Portilla, Pierian Training',
		stars: 3,
		rate: 4,
		rateNumber: '403,83',
		price: 'EL109.99',
		discount: 'EL1,879.99',
		bestSeller: '',
	},
];

export const Customers = [
	{
		id: 1,
		desc: 'Thanks to Udemy Business, Booz Allen has armed our workforce, specifically its',
		desc2: 'that are enabling consultants to stay ahead of big data trends and raise the bar on proficiency, skills, and competencies to meet client demand.',
		specilaDesc:
			'data scientists, with highly relevant and in-demand tech skills',
		img: '/images/customer-story/1.jpeg',
		name: 'Jim Hemgen',
		job: 'Principal',
		address: 'Booz Allen Hamilton',
		fullStoryLink: '/',
		customerLink: '/',
	},
	{
		id: 2,
		desc: 'I am proud to say that after a few months of taking this course...',
		desc2: 'This content was exactly what the CCP exam covered.',
		specilaDesc:
			'I passed my exam and am now an AWS Certified Cloud Practitioner!',
		img: '/images/customer-story/1.jpeg',
		name: 'Jim Hemgen',
		job: 'Principal',
		address: 'Booz Allen Hamilton',
		fullStoryLink: '/',
		customerLink: '/',
	},
	{
		id: 3,
		desc: 'I am proud to say that after a few months of taking this course...',
		desc2: 'This content was exactly what the CCP exam covered.',
		specilaDesc:
			'I passed my exam and am now an AWS Certified Cloud Practitioner!',
		img: '/images/customer-story/1.jpeg',
		name: 'Jim Hemgen',
		job: 'Principal',
		address: 'Booz Allen Hamilton',
		fullStoryLink: '/',
		customerLink: '/',
	},
	{
		id: 4,
		desc: 'I am proud to say that after a few months of taking this course...',
		desc2: 'This content was exactly what the CCP exam covered.',
		specilaDesc:
			'I passed my exam and am now an AWS Certified Cloud Practitioner!',
		img: '/images/customer-story/1.jpeg',
		name: 'Jim Hemgen',
		job: 'Principal',
		address: 'Booz Allen Hamilton',
		fullStoryLink: '/',
		customerLink: '/',
	},
	{
		id: 5,
		desc: 'I am proud to say that after a few months of taking this course...',
		desc2: 'This content was exactly what the CCP exam covered.',
		specilaDesc:
			'I passed my exam and am now an AWS Certified Cloud Practitioner!',
		img: '/images/customer-story/1.jpeg',
		name: 'Jim Hemgen',
		job: 'Principal',
		address: 'Booz Allen Hamilton',
		fullStoryLink: '/',
		customerLink: '/',
	},
	{
		id: 6,
		desc: 'I am proud to say that after a few months of taking this course...',
		desc2: 'This content was exactly what the CCP exam covered.',
		specilaDesc:
			'I passed my exam and am now an AWS Certified Cloud Practitioner!',
		img: '/images/customer-story/1.jpeg',
		name: 'Jim Hemgen',
		job: 'Principal',
		address: 'Booz Allen Hamilton',
		fullStoryLink: '/',
		customerLink: '/',
	},
];

export const Testimoials = [
	{
		id: 1,
		desc: 'I am proud to say that after a few months of taking this course...',
		desc2: 'This content was exactly what the CCP exam covered.',
		specilaDesc:
			'I passed my exam and am now an AWS Certified Cloud Practitioner!',
		name: 'jone mark',
		nameWithLetter: 'j m',
		linkTitle: '[NEW] ultimate AWS certified cloud partitioner - 2022',
		link: '/',
	},
	{
		id: 2,
		desc: 'This course helped me',
		desc2: 'Thanks guys :)',
		specilaDesc:
			'freshen up on my product manager skills and land a job at Facebook!',
		name: 'will peter',
		nameWithLetter: 'w p',
		link: '/',
		linkTitle: 'become a product manager | learn skills & get the job',
	},
	{
		id: 3,
		desc: 'I am proud to say that after a few months of taking this course...',
		desc2: 'This content was exactly what the CCP exam covered.',
		specilaDesc:
			'I passed my exam and am now an AWS Certified Cloud Practitioner!',
		name: 'jone mark',
		nameWithLetter: 'j m',
		linkTitle: '[NEW] ultimate AWS certified cloud partitioner - 2022',
		link: '/',
	},
	{
		id: 4,
		desc: 'from beginner to advanced',
		desc2: 'This content was exactly what the CCP exam covered.',
		specilaDesc:
			'freshen up on my product manager skills and land a job at Facebook!',
		name: 'will peter',
		nameWithLetter: 'w p',
		link: '/',
		linkTitle: 'become a product manager | learn skills & get the job',
	},
	{
		id: 5,
		desc: 'I am proud to say that after a few months of taking this course...',
		desc2: 'This content was exactly what the CCP exam covered.',
		specilaDesc:
			'I passed my exam and am now an AWS Certified Cloud Practitioner!',
		name: 'jone mark',
		nameWithLetter: 'j m',
		linkTitle: '[NEW] ultimate AWS certified cloud partitioner - 2022',
		link: '/',
	},
	{
		id: 6,
		desc: 'from beginner to advanced',
		desc2: 'This content was exactly what the CCP exam covered.',
		specilaDesc:
			'freshen up on my product manager skills and land a job at Facebook!',
		name: 'will peter',
		nameWithLetter: 'w p',
		link: '/',
		linkTitle: 'become a product manager | learn skills & get the job',
	},
];
